### ISSUE TITLE
TypeCastError on getting a key who doesn't exists

### ISSUE THREAD

**Issue by espinozasenior** [ballerina-platform/module-ballerinax-redis#62]
**My Environment**:
macOS Catalina 10.15.6
Ballerina Swan Lake Preview 1
Language specification v2020-06-18
Update Tool 0.8.10

**Line of code**:
`string|redis:Error result = cache->get("test");
  if (result is redis:Error) {
      log:printInfo("Error");
  } else {
      log:printInfo(<string>result);
  }`

**ISSUE**:
The get command works right always and when the key exists in redis, otherwise it prompt the bellow error, there are no way to manage to handle the no-key case.

**Error prompt**:
`error: {ballerina}TypeCastError message=incompatible types: '()' cannot be cast to 'string'
        at ballerinax.redis.0_99_0.Client:get(/src/redis/endpoint.bal:137)`

https://github.com/ballerina-platform/module-ballerinax-redis/blob/7474de6a2b973232b13606243be153cd1c5318ec/redis/src/redis/endpoint.bal#L137

**ballerina-internal.log**
`[2020-11-20 17:27:19,718] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:447)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:438)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lambda$visit$0(SymbolResolver.java:924)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.visit(SymbolResolver.java:929)
	at org.wso2.ballerinalang.compiler.tree.types.BLangUnionTypeNode.accept(BLangUnionTypeNode.java:54)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:447)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.resolveTypeNode(SymbolResolver.java:438)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:1120)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:234)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeVarNode(SemanticAnalyzer.java:627)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:564)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2590)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2558)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2550)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:1601)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2590)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2558)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeStmt(SemanticAnalyzer.java:2554)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:361)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2590)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:333)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2590)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2558)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2550)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.lambda$visit$10(SemanticAnalyzer.java:443)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:442)
	at org.wso2.ballerinalang.compiler.tree.types.BLangObjectTypeNode.accept(BLangObjectTypeNode.java:71)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2590)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2558)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2550)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:387)
	at org.wso2.ballerinalang.compiler.tree.BLangTypeDefinition.accept(BLangTypeDefinition.java:110)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2590)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeNode(SemanticAnalyzer.java:2558)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyzeDef(SemanticAnalyzer.java:2550)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:256)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.analyze(SemanticAnalyzer.java:230)
	at org.wso2.ballerinalang.compiler.CompilerDriver.typeCheck(CompilerDriver.java:322)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:256)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
[2020-11-21 16:41:41,666] SEVERE {b7a.log.crash} - null 
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.lambda$resolveEndpointsFromStatements$9(VisibleEndpointVisitor.java:225)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.resolveEndpointsFromStatements(VisibleEndpointVisitor.java:204)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:122)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:56)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:133)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:134)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangIf.accept(BLangIf.java:56)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.lambda$resolveEndpointsFromStatements$9(VisibleEndpointVisitor.java:231)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.resolveEndpointsFromStatements(VisibleEndpointVisitor.java:204)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:128)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:57)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:108)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.lambda$visit$3(VisibleEndpointVisitor.java:116)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:116)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:126)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.acceptNode(VisibleEndpointVisitor.java:158)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.lambda$visit$1(VisibleEndpointVisitor.java:95)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.ballerinalang.langserver.extensions.VisibleEndpointVisitor.visit(VisibleEndpointVisitor.java:95)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.getVisibleEndpoints(DefaultObservabilitySymbolCollector.java:161)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.getModuleASTHolder(DefaultObservabilitySymbolCollector.java:148)
	at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:87)
	at org.wso2.ballerinalang.compiler.CompilerDriver.generateObservabilityData(CompilerDriver.java:314)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:291)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:248)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:140)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:52)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.RunCommand.execute(RunCommand.java:310)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
 
`

**Comment by SkNuwanTissera** [comment]
Hi @espinozasenior 
Can you please check for this issue now?
Thanks

**Comment by kapilraajP** [comment]
It is addressed in following PR https://github.com/ballerina-platform/module-ballerinax-redis/pull/81

**Comment by abeykoon** [comment]
Closing as addressed.
